### ISSUE TITLE
Could not find any remote files, exiting

### ISSUE THREAD

**Issue by TopBanana123** [DocDrydenn/kiwix-zim#42] opened 2024-12-01 03:39 UTC
For the past 2 days I've gotten the error "Could not find any remote files, exiting" - Is this something with Kiwix or the script?

```
==========================================
 kiwix-zim-updater
       download.kiwix.org ZIM Updater

   v3.3 by DocDrydenn and jojo2357
==========================================

            DRY-RUN/SIMULATION
               - DISABLED -

             !!! Caution !!!

==========================================

1. Checking for Script Updates...

   ✓ Git Clone Detected: Checking Script Version...
   ✓ Version: Current

2. Preprocessing...

  -Validating ZIM directory...
  ✓ Valid ZIM Directory

  -Building online ZIM list...
    ✗  Could not find any remote files, exiting
```

**Comment by jojo2357** [comment] 2024-12-01 03:49
Take a look at `kiwix-index` in the same dir as the script. and share here

I suspect it is empty and not filled with html `link` elements. This can happen when kiwix is unreachable or something weird happens. Cant say I have tested every edge case.

Use `-g` to force fetching the index every time.

**Comment by TopBanana123** [comment] 2024-12-01 03:51
Yep its empty

Tried -g just now, and fails the same. I guess it must be their end?

**Comment by jojo2357** [comment] 2024-12-01 03:56
I just checked, yes the library is unreachable on my end, as well as the index (where I go shopping for my new zims) https://download.kiwix.org/zim/

Found this reddit post on the outage: https://www.reddit.com/r/Kiwix/comments/1h3t3g9/anyone_else_not_able_to_access_the_library/

If you have suggestions on how to better handle this situation, please let me know, otherwise close this issue please.

**Comment by Jaifroid** [comment] 2024-12-01 09:31
Confirmed that library.kiwix.org and download.kiwix.org are currently down. Devs are aware and investigating. However, at least download.kiwix.org was available yesterday (Saturday) afternoon, because I was testing the PWA version on BrowserStack, and ZIMs were downloading fine then. So it hasn't been down for two days, though there might be some intermittent failures, or failure of a specific service.

**Comment by jojo2357** [comment] 2024-12-01 17:01
The script relies on both https://download.kiwix.org/zim/ and "https://library.kiwix.org/catalog/ so it is possible that either one went down first.

**Comment by Swarthe** [comment] 2024-12-03 17:06
I can attest that the library and https://download.kiwix.org are back up.

**Comment by jojo2357** [comment] 2024-12-04 23:35
Nobody suggested any changes, and this is [confirmed to be upstream](https://www.reddit.com/r/Kiwix/comments/1h4yv7y/psa_all_kiwix_master_servers_are_down_were/). Closing

**Closed as not planned by jojo2357** 2024-12-04 23:35 UTC
